param(
    [string]$Root = ".",
    [string]$Entry = "logger.lua",
    [string]$Out = "dist/logger.bundle.lua"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Fail([string]$Message) {
    throw "[bundle-lua] $Message"
}

function To-Posix([string]$PathText) {
    return $PathText.Replace('\', '/')
}

function Remove-LuaExt([string]$PathText) {
    if ($PathText.EndsWith('.lua')) {
        return $PathText.Substring(0, $PathText.Length - 4)
    }
    return $PathText
}

function Get-RelativePathCompat([string]$BasePath, [string]$TargetPath) {
    if ([System.IO.Path].GetMethod('GetRelativePath', [Type[]]@([string], [string]))) {
        return [System.IO.Path]::GetRelativePath($BasePath, $TargetPath)
    }

    $base = [System.IO.Path]::GetFullPath($BasePath)
    if (-not $base.EndsWith([System.IO.Path]::DirectorySeparatorChar)) {
        $base += [System.IO.Path]::DirectorySeparatorChar
    }
    $baseUri = New-Object System.Uri($base)
    $targetUri = New-Object System.Uri([System.IO.Path]::GetFullPath($TargetPath))
    $relative = $baseUri.MakeRelativeUri($targetUri).ToString()
    return [System.Uri]::UnescapeDataString($relative).Replace('/', [System.IO.Path]::DirectorySeparatorChar)
}

$rootDir = (Resolve-Path -Path $Root).Path
$entryAbs = [System.IO.Path]::GetFullPath((Join-Path $rootDir $Entry))

if (-not (Test-Path -Path $entryAbs)) {
    Fail "Entry file not found: $entryAbs"
}

$entryRel = Get-RelativePathCompat -BasePath $rootDir -TargetPath $entryAbs
$entryId = Remove-LuaExt (To-Posix $entryRel)

$moduleMap = [ordered]@{}

function Normalize-ModuleId([string]$FromModuleId, [string]$RawRequire) {
    $clean = To-Posix $RawRequire

    if ($clean.StartsWith('./') -or $clean.StartsWith('../')) {
        $fromDir = [System.IO.Path]::GetDirectoryName($FromModuleId)
        if ([string]::IsNullOrEmpty($fromDir)) {
            $fromDir = "."
        }
        $candidate = [System.IO.Path]::GetFullPath((Join-Path (Join-Path $rootDir $fromDir) $clean))
    } else {
        $candidate = [System.IO.Path]::GetFullPath((Join-Path $rootDir $clean))
    }

    $candidate = Remove-LuaExt $candidate
    $moduleFile = "$candidate.lua"

    if (-not (Test-Path -Path $moduleFile)) {
        Fail "Module not found: require('$RawRequire') from '$FromModuleId' -> expected $moduleFile"
    }

    $rel = Get-RelativePathCompat -BasePath $rootDir -TargetPath $candidate
    return Remove-LuaExt (To-Posix $rel)
}

function Visit([string]$ModuleId) {
    if ($moduleMap.Contains($ModuleId)) {
        return
    }

    $abs = [System.IO.Path]::GetFullPath((Join-Path $rootDir "$ModuleId.lua"))
    if (-not (Test-Path -Path $abs)) {
        Fail "Missing file for module '$ModuleId': $abs"
    }

    $code = Get-Content -Path $abs -Raw -Encoding UTF8
    if ($code.Length -gt 0 -and [int][char]$code[0] -eq 65279) {
        $code = $code.Substring(1)
    }

    $pattern = 'require\s*\(\s*(["''])[ ]*([^"'']+?)[ ]*\1\s*\)'
    $localFrom = $ModuleId
    $code = [regex]::Replace($code, $pattern, {
        param($m)
        $quote = $m.Groups[1].Value
        $reqPath = $m.Groups[2].Value
        $norm = Normalize-ModuleId -FromModuleId $localFrom -RawRequire $reqPath
        Visit -ModuleId $norm
        return "require($quote$norm$quote)"
    })

    $moduleMap[$ModuleId] = $code
}

Visit -ModuleId $entryId

$chunks = New-Object System.Collections.Generic.List[string]
$chunks.Add('-- AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.')
$chunks.Add('-- Generated by scripts/bundle-lua.ps1')
$chunks.Add("-- Entry: $entryId")
$chunks.Add('')
$chunks.Add('local __modules = {}')
$chunks.Add('')

foreach ($k in $moduleMap.Keys) {
    $chunks.Add('__modules["' + $k + '"] = function(require)')
    $chunks.Add($moduleMap[$k])
    $chunks.Add('end')
    $chunks.Add('')
}

$chunks.Add('local __cache = {}')
$chunks.Add('local function require(name)')
$chunks.Add('    local cached = __cache[name]')
$chunks.Add('    if cached ~= nil then return cached end')
$chunks.Add('    local loader = __modules[name]')
$chunks.Add('    if not loader then error("module not found: " .. tostring(name), 2) end')
$chunks.Add('    local value = loader(require)')
$chunks.Add('    if value == nil then value = true end')
$chunks.Add('    __cache[name] = value')
$chunks.Add('    return value')
$chunks.Add('end')
$chunks.Add('')
$chunks.Add('return require("' + $entryId + '")')
$chunks.Add('')

$outAbs = [System.IO.Path]::GetFullPath((Join-Path $rootDir $Out))
$outDir = [System.IO.Path]::GetDirectoryName($outAbs)
if (-not (Test-Path -Path $outDir)) {
    New-Item -Path $outDir -ItemType Directory -Force | Out-Null
}

[System.IO.File]::WriteAllText($outAbs, ($chunks -join "`n"), [System.Text.UTF8Encoding]::new($false))
Write-Host "[bundle-lua] Wrote $outAbs"
Write-Host "[bundle-lua] Modules bundled: $($moduleMap.Count)"
